run-name: Modeling

on:
  push:
    branches:
      - main

jobs:
  Modeling:
    name: Modeling
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        slice: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10]
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Modeling
        run: |
          python ensemble_models.py -t=1 -s=${{ matrix.slice }}
          python ensemble_models.py -t=2 -s=${{ matrix.slice }}
          python ensemble_models.py -t=3 -s=${{ matrix.slice }}
          python ensemble_models.py -t=4 -s=${{ matrix.slice }}

      - name: Commit changes
        run: |
          git add *
          git pull
          git commit -m "Automated update"
          git push
      
      - name: Commit changes (backup)
        if: ${{ failure() }}
        run: |
          git add *
          git pull
          git commit -m "Automated update"
          git push