run-name: Results

on:
  workflow_dispatch:

jobs:
  Modeling:
    name: Modeling
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        slice: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12]
        target: [0, 1, 2, 3]
        oversampling: [0, 1]
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Modeling
        run: |
          python step_0_modeling.py -t=${{ matrix.target }} -s=${{ matrix.slice }} -o=${{ matrix.oversampling }}

      - name: Commit changes
        run: |
          git add models/*
          git pull
          git pull
          git pull
          git pull
          git pull
          git commit -m "Automated update"
          git push

  Analysis:
    name: Analysis
    needs: Modeling
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        slice: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12]
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Analysis
        run: |
          python step_1_analysis.py -s=${{ matrix.slice }}

      - name: Commit changes
        run: |
          git add results/*
          git pull
          git pull
          git pull
          git pull
          git pull
          git commit -m "Automated update"
          git push

  Results:
    name: Results
    needs: Analysis
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Results
        run: python step_2_results.py
      
      - name: Commit changes
        run: |
          git pull
          git add retrain.csv
          git add figures/*
          git commit -m "Automated update"
          git push

  Remodeling:
    name: Remodeling
    needs: Results
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        slice: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
        target: [0, 1, 2, 3]
        oversampling: [0, 1]
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Remodeling
        run: |
          python step_3_modeling.py -t=${{ matrix.target }} -s=${{ matrix.slice }} -o=${{ matrix.oversampling }}

      - name: Commit changes
        run: |
          git add refined_models/*
          git pull
          git pull
          git pull
          git pull
          git pull
          git commit -m "Automated update"
          git push

  Reanalize:
    name: Reanalize
    needs: Remodeling
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        slice: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Reanalize
        run: |
          python step_4_analysis.py -s=${{ matrix.slice }}

      - name: Commit changes
        run: |
          git add results/*
          git pull
          git pull
          git pull
          git pull
          git pull
          git commit -m "Automated update"
          git push

  Reavaliate:
    name: Reavaliate
    needs: Reanalize
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Reavaliate
        run: python step_5_results.py
      
      - name: Commit changes
        run: |
          git pull
          git add final.csv
          git add figures/*
          git commit -m "Automated update"
          git push

  Final_Model:
    name: Final Model
    needs: Reavaliate
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        line: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Final Model
        run: |
          python step_6_modeling.py -l=${{ matrix.line }}

      - name: Commit changes
        run: |
          git add final_models/*
          git pull
          git pull
          git pull
          git pull
          git pull
          git commit -m "Automated update"
          git push

  Final_Results:
    name: Final Results
    needs: Final_Model
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        slice: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Final Results
        run: |
          python step_7_analysis.py

      - name: Commit changes
        run: |
          git add results_final.csv
          git pull
          git commit -m "Automated update"
          git push
