run-name: Results

on:
  workflow_dispatch:

jobs:
  Final_Results:
    name: Final Results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Final Results
        run: |
          python step_7_analysis.py

      - name: Commit changes
        run: |
          git add results_final.csv
          git pull
          git commit -m "Automated update"
          git push
