run-name: Step 5

on:
  workflow_dispatch:

jobs:
  Results:
    name: Results
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Configure repo
        run: |
          git config --global user.name 'IgorMichels'
          git config --global user.email 'igorxadrezbr@gmail.com'
          git pull
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Results
        run: python step_5_results.py
      
      - name: Commit changes
        run: |
          git pull
          git add figures/*
          git commit -m "Automated update"
          git push
